version: '3.8'
services:
  kak_bank:
    container_name: 'deal-kh-api'
    #    image: 'surveybox_stage:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3101:8080'   #follow you port
    volumes:
      - '/home/dealkh/deal-kh-api/filestorage/images:/home/dealkh/filestorage/images'
## what i want to explain to you is like see
#/home/ite/media is inside contianer right
#/home/istad/kak-bank/images on host machine or on server that deploy container