version: '3.8'
services:
  deal-kh-api:
    container_name: 'deal-kh-api'
    #    image: 'surveybox_stage:latest'
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    ports:
      - '3101:8080'   #follow your port
    volumes:
      - deal-kh-api:/home/dealkh/images
      - /home/dealkh/dealkh-api/filestorage/images:/home/dealkh/images
    networks:
      - dealkh
volumes:
  deal-kh-api:
    driver: local
networks:
  dealkh:
    driver: bridge
    ipam:
      config:
        - subnet: 172.82.0.0/16